telegram:
  proxy: "http://185.226.92.131:41625"  # مثال: http://proxy:port
  admin_ids:
    - 5059280908  # user ID ادمین
database:
  path: "cache/v2ray.db"
limits:
  max_configs_per_protocol: 300  # حداکثر لینک برای هر پروتکل
schedule:
  update_interval: 3600  # جمع‌آوری هر 24 ساعت (ثانیه)
  cleanup_interval: 24