telegram:
  admin_ids:
    - 5059280908
database:
  DB_FILE: "cache/v2ray.db"
limits:
  max_configs_per_protocol: 300
schedule:
  update_interval: 86400  # 24 ساعت
  cleanup_interval: 24
proxy:
  sources:
    - "https://www.freeproxy.world/?type=http&anonymity=&country=IR&speed=&port=&page=1"
    - "https://hidemy.name/en/proxy-list/countries/iran"
    - "https://www.proxynova.com/proxy-server-list/country-ir"
    - "http://free-proxy.cz/en/proxylist/country/IR/all/ping/all"
    - "https://www.ditatompel.com/proxy/country/ir"
    - "https://spys.one/free-proxy-list/IR/"
    - "https://proxy-spider.com/proxies/locations/ir-iran"
    - "https://freeproxyupdate.com/iran-ir"
    - "https://premiumproxy.net/top-country-proxy-list/IR-Iran/"